/** @jsx React.DOM */

var GlyphIcon = React.createClass({
	render:function(){
		var className = "glyphicon glyphicon-" + this.props.type + " " + this.props.className;

		return (
			<Icon className={className} textRight={this.props.textRight} textLeft={this.props.textLeft} />
		);
	}
});

function extendIcon(typeClass){
	return React.createClass({
		render:function(){
			return (
				<GlyphIcon
					type={typeClass}
					text={this.props.text}
					textLeft={this.props.textLeft}
					textRight={this.props.textRight}
					spinClass={this.props.spinClass}
					className={this.props.className}
				/>
			);
		}
	});
};

var GlyphIconAsterisk = extendIcon('asterisk');
var GlyphIconPlus = extendIcon('plus');
var GlyphIconEuro = extendIcon('euro');
var GlyphIconMinus = extendIcon('minus');
var GlyphIconCloud = extendIcon('cloud');
var GlyphIconEnvelope = extendIcon('envelope');
var GlyphIconPencil = extendIcon('pencil');
var GlyphIconGlass = extendIcon('glass');
var GlyphIconMusic = extendIcon('music');
var GlyphIconSearch = extendIcon('search');
var GlyphIconHeart = extendIcon('heart');
var GlyphIconStar = extendIcon('star');
var GlyphIconStarEmpty = extendIcon('star-empty');
var GlyphIconUser = extendIcon('user');
var GlyphIconFilm = extendIcon('film');
var GlyphIconThLarge = extendIcon('th-large');
var GlyphIconTh = extendIcon('th');
var GlyphIconThList = extendIcon('th-list');
var GlyphIconOk = extendIcon('ok');
var GlyphIconRemove = extendIcon('remove');
var GlyphIconZoomIn = extendIcon('zoom-in');
var GlyphIconZoomOut = extendIcon('zoom-out');
var GlyphIconOff = extendIcon('off');
var GlyphIconSignal = extendIcon('signal');
var GlyphIconCog = extendIcon('cog');
var GlyphIconTrash = extendIcon('trash');
var GlyphIconHome = extendIcon('home');
var GlyphIconFile = extendIcon('file');
var GlyphIconTime = extendIcon('time');
var GlyphIconRoad = extendIcon('road');
var GlyphIconDownloadAlt = extendIcon('download-alt');
var GlyphIconDownload = extendIcon('download');
var GlyphIconUpload = extendIcon('upload');
var GlyphIconInbox = extendIcon('inbox');
var GlyphIconPlayCircle = extendIcon('play-circle');
var GlyphIconRepeat = extendIcon('repeat');
var GlyphIconRefresh = extendIcon('refresh');
var GlyphIconListAlt = extendIcon('list-alt');
var GlyphIconLock = extendIcon('lock');
var GlyphIconFlag = extendIcon('flag');
var GlyphIconHeadphones = extendIcon('headphones');
var GlyphIconVolumeOff = extendIcon('volume-off');
var GlyphIconVolumeDown = extendIcon('volume-down');
var GlyphIconVolumeUp = extendIcon('volume-up');
var GlyphIconQrcode = extendIcon('qrcode');
var GlyphIconBarcode = extendIcon('barcode');
var GlyphIconTag = extendIcon('tag');
var GlyphIconTags = extendIcon('tags');
var GlyphIconBook = extendIcon('book');
var GlyphIconBookmark = extendIcon('bookmark');
var GlyphIconPrint = extendIcon('print');
var GlyphIconCamera = extendIcon('camera');
var GlyphIconFont = extendIcon('font');
var GlyphIconBold = extendIcon('bold');
var GlyphIconItalic = extendIcon('italic');
var GlyphIconTextHeight = extendIcon('text-height');
var GlyphIconTextWidth = extendIcon('text-width');
var GlyphIconAlignLeft = extendIcon('align-left');
var GlyphIconAlignCenter = extendIcon('align-center');
var GlyphIconAlignRight = extendIcon('align-right');
var GlyphIconAlignJustify = extendIcon('align-justify');
var GlyphIconList = extendIcon('list');
var GlyphIconIndentLeft = extendIcon('indent-left');
var GlyphIconIndentRight = extendIcon('indent-right');
var GlyphIconFacetimeVideo = extendIcon('facetime-video');
var GlyphIconPicture = extendIcon('picture');
var GlyphIconMapMarker = extendIcon('map-marker');
var GlyphIconAdjust = extendIcon('adjust');
var GlyphIconTint = extendIcon('tint');
var GlyphIconEdit = extendIcon('edit');
var GlyphIconShare = extendIcon('share');
var GlyphIconCheck = extendIcon('check');
var GlyphIconMove = extendIcon('move');
var GlyphIconStepBackward = extendIcon('step-backward');
var GlyphIconFastBackward = extendIcon('fast-backward');
var GlyphIconBackward = extendIcon('backward');
var GlyphIconPlay = extendIcon('play');
var GlyphIconPause = extendIcon('pause');
var GlyphIconStop = extendIcon('stop');
var GlyphIconForward = extendIcon('forward');
var GlyphIconFastForward = extendIcon('fast-forward');
var GlyphIconStepForward = extendIcon('step-forward');
var GlyphIconEject = extendIcon('eject');
var GlyphIconChevronLeft = extendIcon('chevron-left');
var GlyphIconChevronRight = extendIcon('chevron-right');
var GlyphIconPlusSign = extendIcon('plus-sign');
var GlyphIconMinusSign = extendIcon('minus-sign');
var GlyphIconRemoveSign = extendIcon('remove-sign');
var GlyphIconOkSign = extendIcon('ok-sign');
var GlyphIconQuestionSign = extendIcon('question-sign');
var GlyphIconInfoSign = extendIcon('info-sign');
var GlyphIconScreenshot = extendIcon('screenshot');
var GlyphIconRemoveCircle = extendIcon('remove-circle');
var GlyphIconOkCircle = extendIcon('ok-circle');
var GlyphIconBanCircle = extendIcon('ban-circle');
var GlyphIconArrowLeft = extendIcon('arrow-left');
var GlyphIconArrowRight = extendIcon('arrow-right');
var GlyphIconArrowUp = extendIcon('arrow-up');
var GlyphIconArrowDown = extendIcon('arrow-down');
var GlyphIconShareAlt = extendIcon('share-alt');
var GlyphIconResizeFull = extendIcon('resize-full');
var GlyphIconResizeSmall = extendIcon('resize-small');
var GlyphIconExclamationSign = extendIcon('exclamation-sign');
var GlyphIconGift = extendIcon('gift');
var GlyphIconLeaf = extendIcon('leaf');
var GlyphIconFire = extendIcon('fire');
var GlyphIconEyeOpen = extendIcon('eye-open');
var GlyphIconEyeClose = extendIcon('eye-close');
var GlyphIconWarningSign = extendIcon('warning-sign');
var GlyphIconPlane = extendIcon('plane');
var GlyphIconCalendar = extendIcon('calendar');
var GlyphIconRandom = extendIcon('random');
var GlyphIconComment = extendIcon('comment');
var GlyphIconMagnet = extendIcon('magnet');
var GlyphIconChevronUp = extendIcon('chevron-up');
var GlyphIconChevronDown = extendIcon('chevron-down');
var GlyphIconRetweet = extendIcon('retweet');
var GlyphIconShoppingCart = extendIcon('shopping-cart');
var GlyphIconFolderClose = extendIcon('folder-close');
var GlyphIconFolderOpen = extendIcon('folder-open');
var GlyphIconResizeVertical = extendIcon('resize-vertical');
var GlyphIconResizeHorizontal = extendIcon('resize-horizontal');
var GlyphIconHdd = extendIcon('hdd');
var GlyphIconBullhorn = extendIcon('bullhorn');
var GlyphIconBell = extendIcon('bell');
var GlyphIconCertificate = extendIcon('certificate');
var GlyphIconThumbsUp = extendIcon('thumbs-up');
var GlyphIconThumbsDown = extendIcon('thumbs-down');
var GlyphIconHandRight = extendIcon('hand-right');
var GlyphIconHandLeft = extendIcon('hand-left');
var GlyphIconHandUp = extendIcon('hand-up');
var GlyphIconHandDown = extendIcon('hand-down');
var GlyphIconCircleArrowRight = extendIcon('circle-arrow-right');
var GlyphIconCircleArrowLeft = extendIcon('circle-arrow-left');
var GlyphIconCircleArrowUp = extendIcon('circle-arrow-up');
var GlyphIconCircleArrowDown = extendIcon('circle-arrow-down');
var GlyphIconGlobe = extendIcon('globe');
var GlyphIconWrench = extendIcon('wrench');
var GlyphIconTasks = extendIcon('tasks');
var GlyphIconFilter = extendIcon('filter');
var GlyphIconBriefcase = extendIcon('briefcase');
var GlyphIconFullscreen = extendIcon('fullscreen');
var GlyphIconDashboard = extendIcon('dashboard');
var GlyphIconPaperclip = extendIcon('paperclip');
var GlyphIconHeartEmpty = extendIcon('heart-empty');
var GlyphIconLink = extendIcon('link');
var GlyphIconPhone = extendIcon('phone');
var GlyphIconPushpin = extendIcon('pushpin');
var GlyphIconUsd = extendIcon('usd');
var GlyphIconGbp = extendIcon('gbp');
var GlyphIconSort = extendIcon('sort');
var GlyphIconSortByAlphabet = extendIcon('sort-by-alphabet');
var GlyphIconSortByAlphabetAlt = extendIcon('sort-by-alphabet-alt');
var GlyphIconSortByOrder = extendIcon('sort-by-order');
var GlyphIconSortByOrderAlt = extendIcon('sort-by-order-alt');
var GlyphIconSortByAttributes = extendIcon('sort-by-attributes');
var GlyphIconSortByAttributesAlt = extendIcon('sort-by-attributes-alt');
var GlyphIconUnchecked = extendIcon('unchecked');
var GlyphIconExpand = extendIcon('expand');
var GlyphIconCollapseDown = extendIcon('collapse-down');
var GlyphIconCollapseUp = extendIcon('collapse-up');
var GlyphIconLogIn = extendIcon('log-in');
var GlyphIconFlash = extendIcon('flash');
var GlyphIconLogOut = extendIcon('log-out');
var GlyphIconNewWindow = extendIcon('new-window');
var GlyphIconRecord = extendIcon('record');
var GlyphIconSave = extendIcon('save');
var GlyphIconOpen = extendIcon('open');
var GlyphIconSaved = extendIcon('saved');
var GlyphIconImport = extendIcon('import');
var GlyphIconExport = extendIcon('export');
var GlyphIconSend = extendIcon('send');
var GlyphIconFloppyDisk = extendIcon('floppy-disk');
var GlyphIconFloppySaved = extendIcon('floppy-saved');
var GlyphIconFloppyRemove = extendIcon('floppy-remove');
var GlyphIconFloppySave = extendIcon('floppy-save');
var GlyphIconFloppyOpen = extendIcon('floppy-open');
var GlyphIconCreditCard = extendIcon('credit-card');
var GlyphIconTransfer = extendIcon('transfer');
var GlyphIconCutlery = extendIcon('cutlery');
var GlyphIconHeader = extendIcon('header');
var GlyphIconCompressed = extendIcon('compressed');
var GlyphIconEarphone = extendIcon('earphone');
var GlyphIconPhoneAlt = extendIcon('phone-alt');
var GlyphIconTower = extendIcon('tower');
var GlyphIconStats = extendIcon('stats');
var GlyphIconSdVideo = extendIcon('sd-video');
var GlyphIconHdVideo = extendIcon('hd-video');
var GlyphIconSubtitles = extendIcon('subtitles');
var GlyphIconSoundStereo = extendIcon('sound-stereo');
var GlyphIconSoundDolby = extendIcon('sound-dolby');
var GlyphIconSound51 = extendIcon('sound-5-1');
var GlyphIconSound61 = extendIcon('sound-6-1');
var GlyphIconSound71 = extendIcon('sound-7-1');
var GlyphIconCopyrightMark = extendIcon('copyright-mark');
var GlyphIconRegistrationMark = extendIcon('registration-mark');
var GlyphIconCloudDownload = extendIcon('cloud-download');
var GlyphIconCloudUpload = extendIcon('cloud-upload');
var GlyphIconTreeConifer = extendIcon('tree-conifer');
var GlyphIconTreeDeciduous = extendIcon('tree-deciduous');